#!/bin/sh -e

TOKEN_FILE=${TOKEN_FILE-/etc/lmp-device-register-token}

if [ ! -f ${TOKEN_FILE} ] ; then
	echo "$0: ERROR: Missing token file ${TOKEN_FILE}"
	exit 1
fi

TOKEN=$(head -n1 ${TOKEN_FILE})
if [ -z "${TOKEN}" ] ; then
	echo "$0: ERROR: ${TOKEN_FILE} is empty"
	exit 1
fi

if [ -f /var/sota/sql.db ] ; then
	echo "$0: ERROR: Device appears to already be registered"
	exit 1
fi

# Done in 2 parts. This first part will remove trailing \n's and make
# the output all space separated. The 2nd part makes it comma separated.
[ -d /var/sota/compose-apps ] && APPS=$(ls /var/sota/compose-apps)
APPS=$(echo ${APPS} | tr ' ' ',')
if [ -n "${APPS}" ] ; then
	echo "$0: Registering with default apps = ${APPS}"
	APPS="-a ${APPS}"
else
	echo "$0: Registering with all available apps"
fi

/usr/bin/lmp-device-register -T ${TOKEN} ${APPS}
