#!/bin/sh -e

TOKEN_FILE=${TOKEN_FILE-/etc/lmp-device-register-token}
TAG=""
HSM=""
NAME=""

if [ -f /etc/sota/tag ] ; then
	# tag file should contain only one tag
	# FoundriesFactory backend supports only
	# single tag for device registration
	TAG=$(</etc/sota/tag)
	TAG="-t ${TAG}"
fi

if [ -n "${USE_HOSTNAME}" ]; then
	NAME="-n $(cat /etc/hostname)"
fi

if [ ! -f ${TOKEN_FILE} ] ; then
	echo "$0: ERROR: Missing token file ${TOKEN_FILE}"
	exit 1
fi

TOKEN=$(head -n1 ${TOKEN_FILE})
if [ -z "${TOKEN}" ] ; then
	echo "$0: ERROR: ${TOKEN_FILE} is empty"
	exit 1
fi

if [ -f /var/sota/sql.db ] ; then
	echo "$0: ERROR: Device appears to already be registered"
	exit 1
fi

# HSM auto registration
if [ -f /etc/sota/hsm ]; then
	. /etc/sota/hsm
	if [ -n "${HSM_PIN}" ] && [ -n "${HSM_SOPIN}" ] && [ -n "${HSM_MODULE}" ]; then
		HSM="--hsm-module ${HSM_MODULE} --hsm-so-pin ${HSM_SOPIN} --hsm-pin ${HSM_PIN}"
	fi
fi

# Done in 2 parts. This first part will remove trailing \n's and make
# the output all space separated. The 2nd part makes it comma separated.
[ -d /var/sota/compose-apps ] && APPS=$(ls /var/sota/compose-apps)
APPS=$(echo ${APPS} | tr ' ' ',')
if [ -n "${APPS}" ] ; then
	echo "$0: Registering with default apps = ${APPS}"
	APPS="-a ${APPS}"
else
	echo "$0: Registering with all available apps"
fi

/usr/bin/lmp-device-register -T ${TOKEN} ${NAME} ${TAG} ${APPS} ${HSM}
