# Allow EFUSE access, used by OP-TEE
YAML_COMPILER_FLAGS:append:zynqmp = " -DENABLE_EFUSE_ACCESS"

# Options set via meta-som at the BSP release
YAML_COMPILER_FLAGS:append:k26 = " -DBOARD_SHUTDOWN_PIN=2 -DBOARD_SHUTDOWN_PIN_STATE=0 -DENABLE_EM -DENABLE_MOD_OVERTEMP -DOVERTEMP_DEGC=90.0 "
