#!/bin/sh
# Copyright (C) 2021 Foundries.io Ltd
# Licensed on MIT

OSTREE_DISTRO="lmp"
FACTORY_RESET_TAG=".factory_reset"
FACTORY_RESET_SOTA_TAG=".factory_reset_sota"

ostree_factory_reset_enabled() {
	return 0
}

factory_reset() {
	keep_sota=$1

	msg "Performing factory reset..."

	# Replace /etc/ with /usr/etc (from deployment)
	rm -rf ${ROOTFS_DIR}/etc
	cp -a ${ROOTFS_DIR}/usr/etc ${ROOTFS_DIR}/

	# Filter of what not to remove (at /var root level)
	FIND_EXCLUDE="! -name '.' ! -name '..' ! -name '${FACTORY_RESET_TAG}' ! -name '${FACTORY_RESET_SOTA_TAG}'"
	if [ "${keep_sota}" = "true" ]; then
		msg "Keeping current ${OSTREE_DISTRO} SOTA content"
		FIND_EXCLUDE="${FIND_EXCLUDE} ! -name 'sota'"
	fi

	# Clear /var, stored under the shared ostree folder, not
	# available after prepare-root (mounted later by systemd)
	# TODO: Handle use case when var is provided via a separated partition
	cd ${ROOTFS_DIR}/sysroot/ostree/deploy/${OSTREE_DISTRO}/var
	eval find . -maxdepth 1 ${FIND_EXCLUDE} -exec rm -rf {} "';'"
	cd - >/dev/null

	# TODO: Erase HSM/Secure storage content?
	# TODO: U-Boot/fiovb env?
}

ostree_factory_reset_run() {
	FACTORY_RESET_TAG_PATH="${ROOTFS_DIR}/sysroot/ostree/deploy/${OSTREE_DISTRO}/var/${FACTORY_RESET_TAG}"
	FACTORY_RESET_SOTA_TAG_PATH="${ROOTFS_DIR}/sysroot/ostree/deploy/${OSTREE_DISTRO}/var/${FACTORY_RESET_SOTA_TAG}"

	# Only run after ostree-prepare-root
	if [ -n "${ROOTFS_DIR}" ] && [ -h "${ROOTFS_DIR}/ostree" ]; then
		if [ -f "${FACTORY_RESET_TAG_PATH}" ]; then
			factory_reset "false"
			rm -f ${FACTORY_RESET_TAG_PATH}
		elif [ -f "${FACTORY_RESET_SOTA_TAG_PATH}" ]; then
			factory_reset "true"
			rm -f ${FACTORY_RESET_SOTA_TAG_PATH}
		fi
	else
		msg "No ostree deployment found"
	fi
}
