#!/bin/sh
# Copyright (C) 2018 Open Source Foundries Ltd.
# Licensed on MIT

ostree_enabled() {
	return 0
}

ostree_run() {
	COMPOSEFS_CONF="/usr/lib/ostree/prepare-root.conf"

	if [ -n "$ROOTFS_DIR" ]; then
		if [ -e "$COMPOSEFS_CONF" ]; then
			if [ -e /etc/ostree/composefs ]; then
				. /etc/ostree/composefs
				ostree_composefs_prepare
			fi
		fi

		msg "Preparing OSTree root at '$ROOTFS_DIR'..."
		/usr/lib/ostree/ostree-prepare-root $ROOTFS_DIR
	else
		debug "No rootfs has been set"
	fi
}
