#!/bin/sh

# Force compose down, restart docker and try again

for app in `ls /var/sota/compose-apps` ; do
	cd /var/sota/compose-apps/${app}
	docker compose down
done

# TODO: extend with support for restorable-apps, which should
# allow us to remove /var/lib/docker completely

systemctl restart docker
systemctl reset-failed compose-apps-early-start.service
systemctl restart compose-apps-early-start.service
