#!/bin/sh -e

start_compose_app() {
	app=$1
	cd /var/sota/compose-apps/${app}

	echo "Starting app ${app}"
	ret=0
	docker compose up -d || ret=${?}
	if [ ${ret} -ne 0 ] ; then
		echo "Failed to start app ${app}, trying compose down / up"
		docker compose down
		docker compose up -d
	fi
}

start_compose_apps() {
	if [ -f /var/lmp/default-apps ] ; then
		if [ -d /var/sota/compose-apps ] ; then
			for x in $(ls /var/sota/compose-apps) ; do
				if ! grep -q $x /var/lmp/default-apps 2>/dev/null ; then
					echo "Disabling preloaded app: $x"
					rm -rf /var/sota/compose-apps/$x
				fi
			done
		fi
	fi

	if [ -d /var/sota/compose-apps ] ; then
		for app in `ls /var/sota/compose-apps` ; do
			start_compose_app ${app}
		done
	else
		echo "No apps defined"
	fi
}

start_restorable_apps() {
	default_apps_path="/var/lmp/default-apps"
	shortlist=""

	if [ -f $default_apps_path ] ; then
		for app in `cat $default_apps_path`; do
			if [ -e "/var/sota/compose-apps/${app}" ] ; then
				start_compose_app ${app}
			else
				shortlist="${shortlist}${app},"
			fi
		done
		if [ ! -z $shortlist ] ; then
			shortlist=${shortlist::-1}
                fi
	fi

	if [ -z "${shortlist}" ] ; then
		all=`ls /var/sota/compose-apps 2> /dev/null`
		if [ -n "${all}" ] ; then
			for app in ${all} ; do
				start_compose_app ${app}
			done
		else
			composectl run --apps "${shortlist}"
		fi
	else
		composectl run --apps "${shortlist}"
	fi
}

if [ -d /var/sota/reset-apps ] ; then
	start_restorable_apps
else
	start_compose_apps
fi
