export sites="github.com/Masterminds/semver/v3:github.com/Masterminds/semver/v3 \
           github.com/Microsoft/go-winio:github.com/Microsoft/go-winio \
           github.com/Microsoft/hcsshim:github.com/Microsoft/hcsshim \
           github.com/compose-spec/compose-go:github.com/compose-spec/compose-go \
           github.com/containerd/accelerated-container-image:github.com/containerd/accelerated-container-image \
           github.com/containerd/cgroups:github.com/containerd/cgroups \
           github.com/containerd/cgroups/v3:github.com/containerd/cgroups/v3 \
           github.com/containerd/console:github.com/containerd/console \
           github.com/containerd/containerd:github.com/containerd/containerd \
           github.com/containerd/continuity:github.com/containerd/continuity \
           github.com/containerd/go-cni:github.com/containerd/go-cni \
           github.com/containerd/imgcrypt:github.com/containerd/imgcrypt \
           github.com/containerd/nydus-snapshotter:github.com/containerd/nydus-snapshotter \
           github.com/containerd/stargz-snapshotter:github.com/containerd/stargz-snapshotter \
           github.com/containerd/stargz-snapshotter/estargz:github.com/containerd/stargz-snapshotter//estargz \
           github.com/containerd/stargz-snapshotter/ipfs:github.com/containerd/stargz-snapshotter//ipfs \
           github.com/containerd/typeurl/v2:github.com/containerd/typeurlv2 \
           github.com/containerd/typeurl:github.com/containerd/typeurl \
           github.com/containernetworking/cni:github.com/containernetworking/cni \
           github.com/containernetworking/plugins:github.com/containernetworking/plugins \
           github.com/coreos/go-systemd/v22:github.com/coreos/go-systemd/v22 \
           github.com/cyphar/filepath-securejoin:github.com/cyphar/filepath-securejoin \
           github.com/docker/cli:github.com/docker/cli \
           github.com/docker/docker:github.com/docker/docker \
           github.com/docker/go-connections:github.com/docker/go-connections \
           github.com/docker/go-units:github.com/docker/go-units \
           github.com/fahedouch/go-logrotate:github.com/fahedouch/go-logrotate \
           github.com/fatih/color:github.com/fatih/color \
           github.com/fluent/fluent-logger-golang:github.com/fluent/fluent-logger-golang \
           github.com/hashicorp/go-multierror:github.com/hashicorp/go-multierror \
           github.com/ipfs/go-cid:github.com/ipfs/go-cid \
           github.com/mattn/go-isatty:github.com/mattn/go-isatty \
           github.com/mitchellh/mapstructure:github.com/mitchellh/mapstructure \
           github.com/moby/sys/mount:github.com/moby/sys/mount//mount \
           github.com/moby/sys/signal:github.com/moby/sys/signal//signal \
           github.com/moby/sys/mountinfo:github.com/moby/sys/mountinfo//mountinfo \
           github.com/moby/sys/sequential:github.com/moby/sys/sequential//sequential \
           github.com/moby/sys/symlink:github.com/moby/sys/symlink//symlink \
           github.com/opencontainers/go-digest:github.com/opencontainers/go-digest \
           github.com/opencontainers/image-spec:github.com/opencontainers/image-spec \
           github.com/opencontainers/runtime-spec:github.com/opencontainers/runtime-spec \
           github.com/pelletier/go-toml:github.com/pelletier/go-toml \
           github.com/rootless-containers/bypass4netns:github.com/rootless-containers/bypass4netns \
           github.com/rootless-containers/rootlesskit:github.com/rootless-containers/rootlesskit \
           github.com/sirupsen/logrus:github.com/sirupsen/logrus \
           github.com/spf13/cobra:github.com/spf13/cobra \
           github.com/spf13/pflag:github.com/spf13/pflag \
           github.com/tidwall/gjson:github.com/tidwall/gjson \
           github.com/vishvananda/netlink:github.com/vishvananda/netlink \
           github.com/vishvananda/netns:github.com/vishvananda/netns \
           github.com/yuchanns/srslog:github.com/yuchanns/srslog \
           golang.org/x/crypto:golang.org/x/crypto \
           golang.org/x/net:golang.org/x/net \
           golang.org/x/sync:golang.org/x/sync \
           golang.org/x/sys:golang.org/x/sys \
           golang.org/x/term:golang.org/x/term \
           golang.org/x/text:golang.org/x/text \
           gopkg.in/yaml.v3:gopkg.in/yaml.v3 \
           gotest.tools/v3:github.com/gotestyourself/gotest.tools \
           github.com/AdaLogics/go-fuzz-headers:github.com/AdaLogics/go-fuzz-headers \
           github.com/AdamKorcz/go-118-fuzz-build:github.com/AdamKorcz/go-118-fuzz-build \
           github.com/cilium/ebpf:github.com/cilium/ebpf \
           github.com/containerd/fifo:github.com/containerd/fifo \
           github.com/containerd/ttrpc:github.com/containerd/ttrpc \
           github.com/containers/ocicrypt:github.com/containers/ocicrypt \
           github.com/distribution/distribution/v3:github.com/distribution/distribution/v3 \
           github.com/djherbis/times:github.com/djherbis/times \
           github.com/docker/docker-credential-helpers:github.com/docker/docker-credential-helpers \
           github.com/docker/go-events:github.com/docker/go-events \
           github.com/frankban/quicktest:github.com/frankban/quicktest \
           github.com/go-logr/logr:github.com/go-logr/logr \
           github.com/go-logr/stdr:github.com/go-logr/stdr \
           github.com/godbus/dbus/v5:github.com/godbus/dbus/v5 \
           github.com/gogo/protobuf:github.com/gogo/protobuf \
           github.com/golang/groupcache:github.com/golang/groupcache \
           github.com/golang/protobuf:github.com/golang/protobuf \
           github.com/google/go-cmp:github.com/google/go-cmp \
           github.com/google/uuid:github.com/google/uuid \
           github.com/hashicorp/errwrap:github.com/hashicorp/errwrap \
           github.com/imdario/mergo:github.com/imdario/mergo \
           github.com/inconshreveable/mousetrap:github.com/inconshreveable/mousetrap \
           github.com/klauspost/compress:github.com/klauspost/compress \
           github.com/klauspost/cpuid/v2:github.com/klauspost/cpuid/v2 \
           github.com/mattn/go-colorable:github.com/mattn/go-colorable \
           github.com/mattn/go-shellwords:github.com/mattn/go-shellwords \
           github.com/miekg/pkcs11:github.com/miekg/pkcs11 \
           github.com/minio/sha256-simd:github.com/minio/sha256-simd \
           github.com/mitchellh/go-homedir:github.com/mitchellh/go-homedir \
           github.com/moby/locker:github.com/moby/locker \
           github.com/mr-tron/base58:github.com/mr-tron/base58 \
           github.com/multiformats/go-base32:github.com/multiformats/go-base32 \
           github.com/multiformats/go-base36:github.com/multiformats/go-base36 \
           github.com/multiformats/go-multiaddr:github.com/multiformats/go-multiaddr \
           github.com/multiformats/go-multibase:github.com/multiformats/go-multibase \
           github.com/multiformats/go-multihash:github.com/multiformats/go-multihash \
           github.com/multiformats/go-varint:github.com/multiformats/go-varint \
           github.com/opencontainers/runc:github.com/opencontainers/runc \
           github.com/opencontainers/selinux:github.com/opencontainers/selinux \
           github.com/philhofer/fwd:github.com/philhofer/fwd \
           github.com/pkg/errors:github.com/pkg/errors \
           github.com/spaolacci/murmur3:github.com/spaolacci/murmur3 \
           github.com/stefanberger/go-pkcs11uri:github.com/stefanberger/go-pkcs11uri \
           github.com/tidwall/match:github.com/tidwall/match \
           github.com/tidwall/pretty:github.com/tidwall/pretty \
           github.com/tinylib/msgp:github.com/tinylib/msgp \
           github.com/vbatts/tar-split:github.com/vbatts/tar-split \
           github.com/xeipuuv/gojsonpointer:github.com/xeipuuv/gojsonpointer \
           github.com/xeipuuv/gojsonreference:github.com/xeipuuv/gojsonreference \
           github.com/xeipuuv/gojsonschema:github.com/xeipuuv/gojsonschema \
           go.mozilla.org/pkcs7:go.mozilla.org/pkcs7 \
           go.opencensus.io:go.opencensus.io \
           go.opentelemetry.io/otel:go.opentelemetry.io/otel \
           go.opentelemetry.io/otel/trace:go.opentelemetry.io/otel//trace \
           golang.org/x/mod:golang.org/x/mod \
           golang.org/x/tools:golang.org/x/tools \
           google.golang.org/genproto:github.com/googleapis/go-genproto \
           google.golang.org/grpc:github.com/grpc/grpc-go \
           google.golang.org/protobuf:github.com/protocolbuffers/protobuf-go \
           gopkg.in/square/go-jose.v2:gopkg.in/square/go-jose.v2 \
           lukechampine.com/blake3:lukechampine.com/blake3"


do_compile:prepend() {
    cd ${S}/src/import
    for s in $sites; do
        site_dest=$(echo $s | cut -d: -f1)
        site_source=$(echo $s | cut -d: -f2)
        force_flag=$(echo $s | cut -d: -f3)
        mkdir -p vendor.copy/$site_dest
        if [ -n "$force_flag" ]; then
	    echo "[INFO] $site_dest: force copying .go files"
	    rm -rf vendor.copy/$site_dest
	    rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest
        else
            [ -n "$(ls -A vendor.copy/$site_dest/*.go 2> /dev/null)" ] && { echo "[INFO] vendor.fetch/$site_source -> $site_dest: go copy skipped (files present)" ; true ; } || { echo "[INFO] $site_dest: copying .go files" ; rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest ; }
        fi
    done
}
