# 	github.com/Masterminds/semver/v3 v3.1.1
# [1] git ls-remote https://github.com/Masterminds/semver 7bb0c843b53d6ad21a3f619cb22c4b442bb3ef3e 
SRCREV_v3="7bb0c843b53d6ad21a3f619cb22c4b442bb3ef3e"
SRC_URI += "git://github.com/Masterminds/semver;name=v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Masterminds/semver/v3"

# 	github.com/Microsoft/go-winio v0.5.2
# [1] git ls-remote https://github.com/Microsoft/go-winio dfd7da8f92a382999d77b5d9cfe8cc6bec1894c6 
SRCREV_go-winio="dfd7da8f92a382999d77b5d9cfe8cc6bec1894c6"
SRC_URI += "git://github.com/Microsoft/go-winio;name=go-winio;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/go-winio"

# 	github.com/compose-spec/compose-go v1.4.0
# [1] git ls-remote https://github.com/compose-spec/compose-go 1656887c43be8eb8177f7b72ba4d5581ece50cc2 
SRCREV_compose-go="1656887c43be8eb8177f7b72ba4d5581ece50cc2"
SRC_URI += "git://github.com/compose-spec/compose-go;name=compose-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/compose-spec/compose-go"

# 	github.com/containerd/cgroups v1.0.4
# [1] git ls-remote https://github.com/containerd/cgroups 188f73d13086fdfc4a26bdda70f0362203552e3a 
SRCREV_cgroups="188f73d13086fdfc4a26bdda70f0362203552e3a"
SRC_URI += "git://github.com/containerd/cgroups;name=cgroups;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/cgroups"

# 	github.com/containerd/console v1.0.3
# [1] git ls-remote https://github.com/containerd/console b5cb846c9186d67bcae3ce3c324e47cd317d9527 
SRCREV_console="b5cb846c9186d67bcae3ce3c324e47cd317d9527"
SRC_URI += "git://github.com/containerd/console;name=console;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/console"

# 	github.com/containerd/continuity v0.3.0
# [1] git ls-remote https://github.com/containerd/continuity 5ad51c7aca47b8e742f5e6e7dc841d50f5f6affd 
SRCREV_continuity="5ad51c7aca47b8e742f5e6e7dc841d50f5f6affd"
SRC_URI += "git://github.com/containerd/continuity;name=continuity;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/continuity"

# 	github.com/containerd/go-cni v1.1.7
# [1] git ls-remote https://github.com/containerd/go-cni 2c7e7570ca329c4917c93f5cfa2b1cf1a633c155 
SRCREV_go-cni="2c7e7570ca329c4917c93f5cfa2b1cf1a633c155"
SRC_URI += "git://github.com/containerd/go-cni;name=go-cni;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/go-cni"

# 	github.com/containerd/imgcrypt v1.1.6
# [1] git ls-remote https://github.com/containerd/imgcrypt 23f077229f2cdee91ba70d49684751187a5775f5 
SRCREV_imgcrypt="23f077229f2cdee91ba70d49684751187a5775f5"
SRC_URI += "git://github.com/containerd/imgcrypt;name=imgcrypt;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/imgcrypt"

# 	github.com/containerd/nydus-snapshotter v0.3.0-alpha.5
# [1] git ls-remote https://github.com/containerd/nydus-snapshotter c360523a8a781eed2efc53bfa2e8ee05bf3a7a54 
SRCREV_nydus-snapshotter="c360523a8a781eed2efc53bfa2e8ee05bf3a7a54"
SRC_URI += "git://github.com/containerd/nydus-snapshotter;name=nydus-snapshotter;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/nydus-snapshotter"

# 	github.com/containerd/stargz-snapshotter v0.12.0
# [1] git ls-remote https://github.com/containerd/stargz-snapshotter 461aaf7075bd3f771d6a379eff2db071dd54d222 
SRCREV_stargz-snapshotter="461aaf7075bd3f771d6a379eff2db071dd54d222"
SRC_URI += "git://github.com/containerd/stargz-snapshotter;name=stargz-snapshotter;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/stargz-snapshotter"

# 	github.com/containerd/typeurl v1.0.3-0.20220422153119-7f6e6d160d67
# [1] git ls-remote https://github.com/containerd/typeurl 7f6e6d160d675241af388d5cf1b90814786bac40 
SRCREV_typeurl="7f6e6d160d675241af388d5cf1b90814786bac40"
SRC_URI += "git://github.com/containerd/typeurl;name=typeurl;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/typeurl"

# 	github.com/containernetworking/cni v1.1.2
# [1] git ls-remote https://github.com/containernetworking/cni 3363d143688bb83ca18489ac8b9dc204c1d49c4a 
SRCREV_cni="3363d143688bb83ca18489ac8b9dc204c1d49c4a"
SRC_URI += "git://github.com/containernetworking/cni;name=cni;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containernetworking/cni"

# 	github.com/containernetworking/plugins v1.1.1
# [1] git ls-remote https://github.com/containernetworking/plugins 4744ec27b89c083194e7df498de50f03a8a1d3ec 
SRCREV_plugins="4744ec27b89c083194e7df498de50f03a8a1d3ec"
SRC_URI += "git://github.com/containernetworking/plugins;name=plugins;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containernetworking/plugins"

# 	github.com/coreos/go-systemd/v22 v22.3.2
# [1] git ls-remote https://github.com/coreos/go-systemd 777e73a89cef78631ccaa97f53a9bae67e166186 
SRCREV_v22="777e73a89cef78631ccaa97f53a9bae67e166186"
SRC_URI += "git://github.com/coreos/go-systemd;name=v22;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/coreos/go-systemd/v22"

# 	github.com/cyphar/filepath-securejoin v0.2.3
# [1] git ls-remote https://github.com/cyphar/filepath-securejoin 8f267f5ea675a20a2cb5e91011d063721f53bf79 
SRCREV_filepath-securejoin="8f267f5ea675a20a2cb5e91011d063721f53bf79"
SRC_URI += "git://github.com/cyphar/filepath-securejoin;name=filepath-securejoin;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cyphar/filepath-securejoin"

# 	github.com/docker/cli v20.10.17+incompatible
# [1] git ls-remote https://github.com/docker/cli 100c70180fde3601def79a59cc3e996aa553c9b9 
SRCREV_cli="100c70180fde3601def79a59cc3e996aa553c9b9"
SRC_URI += "git://github.com/docker/cli;name=cli;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/cli"

# 	github.com/docker/docker v20.10.17+incompatible
# [1] git ls-remote https://github.com/docker/docker a89b84221c8560e7a3dee2a653353429e7628424 
SRCREV_docker="a89b84221c8560e7a3dee2a653353429e7628424"
SRC_URI += "git://github.com/docker/docker;name=docker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker"

# 	github.com/docker/go-connections v0.4.0
# [1] git ls-remote https://github.com/docker/go-connections 7395e3f8aa162843a74ed6d48e79627d9792ac55 
SRCREV_go-connections="7395e3f8aa162843a74ed6d48e79627d9792ac55"
SRC_URI += "git://github.com/docker/go-connections;name=go-connections;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-connections"

# 	github.com/docker/go-units v0.4.0
# [1] git ls-remote https://github.com/docker/go-units 519db1ee28dcc9fd2474ae59fca29a810482bfb1 
SRCREV_go-units="519db1ee28dcc9fd2474ae59fca29a810482bfb1"
SRC_URI += "git://github.com/docker/go-units;name=go-units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-units"

# 	github.com/fahedouch/go-logrotate v0.1.2
# [1] git ls-remote https://github.com/fahedouch/go-logrotate 12635ce7ea51353ca82a59bf8ef253bb02ccba28 
SRCREV_go-logrotate="12635ce7ea51353ca82a59bf8ef253bb02ccba28"
SRC_URI += "git://github.com/fahedouch/go-logrotate;name=go-logrotate;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fahedouch/go-logrotate"

# 	github.com/fatih/color v1.13.0
# [1] git ls-remote https://github.com/fatih/color a05da93ebe62ca9fc6791d3376ec4dad01196448 
SRCREV_color="a05da93ebe62ca9fc6791d3376ec4dad01196448"
SRC_URI += "git://github.com/fatih/color;name=color;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fatih/color"

# 	github.com/hashicorp/go-multierror v1.1.1
# [1] git ls-remote https://github.com/hashicorp/go-multierror 9974e9ec57696378079ecc3accd3d6f29401b3a0 
SRCREV_go-multierror="9974e9ec57696378079ecc3accd3d6f29401b3a0"
SRC_URI += "git://github.com/hashicorp/go-multierror;name=go-multierror;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-multierror"

# 	github.com/ipfs/go-cid v0.1.0
# [1] git ls-remote https://github.com/ipfs/go-cid de6c03deae1cf9c032be7f24b83bc7da7d139844 
SRCREV_go-cid="de6c03deae1cf9c032be7f24b83bc7da7d139844"
SRC_URI += "git://github.com/ipfs/go-cid;name=go-cid;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-cid"

# 	github.com/ipfs/go-ipfs-files v0.1.1
# [1] git ls-remote https://github.com/ipfs/go-ipfs-files 5044b18695cb23ae69632c3e2511b4624a87b0d5 
SRCREV_go-ipfs-files="5044b18695cb23ae69632c3e2511b4624a87b0d5"
SRC_URI += "git://github.com/ipfs/go-ipfs-files;name=go-ipfs-files;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipfs-files"

# 	github.com/ipfs/go-ipfs-http-client v0.4.0
# [1] git ls-remote https://github.com/ipfs/go-ipfs-http-client 9c9f43fd9ca36c7ebdc664bb6936a6fe9881255b 
SRCREV_go-ipfs-http-client="9c9f43fd9ca36c7ebdc664bb6936a6fe9881255b"
SRC_URI += "git://github.com/ipfs/go-ipfs-http-client;name=go-ipfs-http-client;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipfs-http-client"

# 	github.com/ipfs/interface-go-ipfs-core v0.7.0
# [1] git ls-remote https://github.com/ipfs/interface-go-ipfs-core a3374d99028d96a1ef262b81acb385690eb36f97 
SRCREV_interface-go-ipfs-core="a3374d99028d96a1ef262b81acb385690eb36f97"
SRC_URI += "git://github.com/ipfs/interface-go-ipfs-core;name=interface-go-ipfs-core;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/interface-go-ipfs-core"

# 	github.com/mattn/go-isatty v0.0.14
# [1] git ls-remote https://github.com/mattn/go-isatty 504425e14f742f1f517c4586048b49b37f829c8e 
SRCREV_go-isatty="504425e14f742f1f517c4586048b49b37f829c8e"
SRC_URI += "git://github.com/mattn/go-isatty;name=go-isatty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-isatty"

# 	github.com/moby/sys/mount v0.3.3
# [1] git ls-remote https://github.com/moby/sys 416188aff8404d549e1e34a50e513befeb11c3b9 
SRCREV_mount="416188aff8404d549e1e34a50e513befeb11c3b9"
SRC_URI += "git://github.com/moby/sys;name=mount;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/mount"

# 	github.com/multiformats/go-multiaddr v0.6.0
# [1] git ls-remote https://github.com/multiformats/go-multiaddr 043a1ee9c857a69f9fa473a9155fae7aa11ca15c 
SRCREV_go-multiaddr="043a1ee9c857a69f9fa473a9155fae7aa11ca15c"
SRC_URI += "git://github.com/multiformats/go-multiaddr;name=go-multiaddr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/multiformats/go-multiaddr"

# 	github.com/opencontainers/go-digest v1.0.0
# [1] git ls-remote https://github.com/opencontainers/go-digest ea51bea511f75cfa3ef6098cc253c5c3609b037a 
SRCREV_go-digest="ea51bea511f75cfa3ef6098cc253c5c3609b037a"
SRC_URI += "git://github.com/opencontainers/go-digest;name=go-digest;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/go-digest"

# 	github.com/opencontainers/image-spec v1.0.3-0.20220303224323-02efb9a75ee1
# [1] git ls-remote https://github.com/opencontainers/image-spec 02efb9a75ee11e05937b535cc5f228f9343ab2f5 
SRCREV_image-spec="02efb9a75ee11e05937b535cc5f228f9343ab2f5"
SRC_URI += "git://github.com/opencontainers/image-spec;name=image-spec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/image-spec"

# 	github.com/opencontainers/runtime-spec v1.0.3-0.20220311020903-6969a0a09ab1
# [1] git ls-remote https://github.com/opencontainers/runtime-spec 6969a0a09ab162a574cafcc9ac814e498962c943 
SRCREV_runtime-spec="6969a0a09ab162a574cafcc9ac814e498962c943"
SRC_URI += "git://github.com/opencontainers/runtime-spec;name=runtime-spec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/runtime-spec"

# 	github.com/pelletier/go-toml v1.9.5
# [1] git ls-remote https://github.com/pelletier/go-toml fed1464066413075eac02cd4dc368b5221845541 
SRCREV_go-toml="fed1464066413075eac02cd4dc368b5221845541"
SRC_URI += "git://github.com/pelletier/go-toml;name=go-toml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pelletier/go-toml"

# 	github.com/rootless-containers/bypass4netns v0.2.2
# [1] git ls-remote https://github.com/rootless-containers/bypass4netns 6fa198e7d1bf58c35ebfb147bc16adede888f3b8 
SRCREV_bypass4netns="6fa198e7d1bf58c35ebfb147bc16adede888f3b8"
SRC_URI += "git://github.com/rootless-containers/bypass4netns;name=bypass4netns;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/rootless-containers/bypass4netns"

# 	github.com/rootless-containers/rootlesskit v1.0.1
# [1] git ls-remote https://github.com/rootless-containers/rootlesskit 5d5f4c0c26e26a6b51d1838c23e793e5836442d0 
SRCREV_rootlesskit="5d5f4c0c26e26a6b51d1838c23e793e5836442d0"
SRC_URI += "git://github.com/rootless-containers/rootlesskit;name=rootlesskit;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/rootless-containers/rootlesskit"

# 	github.com/sirupsen/logrus v1.9.0
# [1] git ls-remote https://github.com/sirupsen/logrus f8bf7650dccb756cea26edaf9217aab85500fe07 
SRCREV_logrus="f8bf7650dccb756cea26edaf9217aab85500fe07"
SRC_URI += "git://github.com/sirupsen/logrus;name=logrus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/sirupsen/logrus"

# 	github.com/spf13/cobra v1.5.0
# [1] git ls-remote https://github.com/spf13/cobra 06b06a9dc9f9f5eba93c552b2532a3da64ef9877 
SRCREV_cobra="06b06a9dc9f9f5eba93c552b2532a3da64ef9877"
SRC_URI += "git://github.com/spf13/cobra;name=cobra;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cobra"

# 	github.com/spf13/pflag v1.0.5
# [1] git ls-remote https://github.com/spf13/pflag 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab 
SRCREV_pflag="2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag;name=pflag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/pflag"

# 	github.com/tidwall/gjson v1.14.1
# [1] git ls-remote https://github.com/tidwall/gjson c3bb2c39ba202da03b359abb4b61555368dc3afb 
SRCREV_gjson="c3bb2c39ba202da03b359abb4b61555368dc3afb"
SRC_URI += "git://github.com/tidwall/gjson;name=gjson;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tidwall/gjson"

# 	github.com/vishvananda/netlink v1.2.1-beta.2
# [1] git ls-remote https://github.com/vishvananda/netlink 5e915e0149386ce3d02379ff93f4c0a5601779d5 
SRCREV_netlink="5e915e0149386ce3d02379ff93f4c0a5601779d5"
SRC_URI += "git://github.com/vishvananda/netlink;name=netlink;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/vishvananda/netlink"

# 	github.com/vishvananda/netns v0.0.0-20211101163701-50045581ed74
# [1] git ls-remote https://github.com/vishvananda/netns 50045581ed74c15eded78746bae9fb3df07d6655 
SRCREV_netns="50045581ed74c15eded78746bae9fb3df07d6655"
SRC_URI += "git://github.com/vishvananda/netns;name=netns;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/vishvananda/netns"

# 	golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e
# [1] git ls-remote https://github.com/golang/crypto 793ad666bf5ec61392092b27061be9618e4e219b 
SRCREV_crypto="793ad666bf5ec61392092b27061be9618e4e219b"
SRC_URI += "git://github.com/golang/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/crypto"

# 	golang.org/x/net v0.0.0-20220615171555-694bf12d69de
# [1] git ls-remote https://github.com/golang/net 694bf12d69de87b859d3663757617cec92450753 
SRCREV_net="694bf12d69de87b859d3663757617cec92450753"
SRC_URI += "git://github.com/golang/net;name=net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/net"

# 	golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4
# [1] git ls-remote https://github.com/golang/sync 886fb9371eb4b47af10bff9c8025a8c9e1554b92 
SRCREV_sync="886fb9371eb4b47af10bff9c8025a8c9e1554b92"
SRC_URI += "git://github.com/golang/sync;name=sync;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sync"

# 	golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8
# [1] git ls-remote https://github.com/golang/sys c0bba94af5f85fbad9f6dc2e04ed5b8fac9696cf 
SRCREV_sys="c0bba94af5f85fbad9f6dc2e04ed5b8fac9696cf"
SRC_URI += "git://github.com/golang/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

# 	golang.org/x/term v0.0.0-20220526004731-065cf7ba2467
# [1] git ls-remote https://github.com/golang/term 065cf7ba2467924044800341704ad654f62c4e6f 
SRCREV_term="065cf7ba2467924044800341704ad654f62c4e6f"
SRC_URI += "git://github.com/golang/term;name=term;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/term"

# 	gopkg.in/yaml.v3 v3.0.1
# [1] git ls-remote https://gopkg.in/yaml.v3 f6f7691b1fdeb513f56608cd2c32c51f8194bf51 
SRCREV_yaml.v3="f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://gopkg.in/yaml.v3;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

# 	gotest.tools/v3 v3.3.0
# [1] git ls-remote https://github.com/gotestyourself/gotest.tools 4de0c9f9fc73d14fda60ea865b44f2cce35346fd 
SRCREV_v31="4de0c9f9fc73d14fda60ea865b44f2cce35346fd"
SRC_URI += "git://github.com/gotestyourself/gotest.tools;name=v31;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gotestyourself/gotest.tools"

# 	github.com/AdaLogics/go-fuzz-headers v0.0.0-20210715213245-6c3934b029d8
# [1] git ls-remote https://github.com/AdaLogics/go-fuzz-headers 6c3934b029d8c261ab9b15482e4d2d00df79b7f7 
SRCREV_go-fuzz-headers="6c3934b029d8c261ab9b15482e4d2d00df79b7f7"
SRC_URI += "git://github.com/AdaLogics/go-fuzz-headers;name=go-fuzz-headers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/AdaLogics/go-fuzz-headers"

# 	github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1
# [1] git ls-remote https://github.com/Azure/go-ansiterm d185dfc1b5a126116ea5a19e148e29d16b4574c9 
SRCREV_go-ansiterm="d185dfc1b5a126116ea5a19e148e29d16b4574c9"
SRC_URI += "git://github.com/Azure/go-ansiterm;name=go-ansiterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Azure/go-ansiterm"

# 	github.com/Microsoft/hcsshim v0.9.3
# [1] git ls-remote https://github.com/Microsoft/hcsshim 50b68e6734cd2f2003689c1037141f58f23db229 
SRCREV_hcsshim="50b68e6734cd2f2003689c1037141f58f23db229"
SRC_URI += "git://github.com/Microsoft/hcsshim;name=hcsshim;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/hcsshim"

# 	github.com/beorn7/perks v1.0.1
# [1] git ls-remote https://github.com/beorn7/perks 37c8de3658fcb183f997c4e13e8337516ab753e6 
SRCREV_perks="37c8de3658fcb183f997c4e13e8337516ab753e6"
SRC_URI += "git://github.com/beorn7/perks;name=perks;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/beorn7/perks"

# 	github.com/blang/semver v3.5.1+incompatible
# [1] git ls-remote https://github.com/blang/semver 2ee87856327ba09384cabd113bc6b5d174e9ec0f 
SRCREV_semver="2ee87856327ba09384cabd113bc6b5d174e9ec0f"
SRC_URI += "git://github.com/blang/semver;name=semver;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/blang/semver"

# 	github.com/bmizerany/assert v0.0.0-20160611221934-b7ed37b82869
# [1] git ls-remote https://github.com/bmizerany/assert b7ed37b82869576c289d7d97fb2bbd8b64a0cb28 
SRCREV_assert="b7ed37b82869576c289d7d97fb2bbd8b64a0cb28"
SRC_URI += "git://github.com/bmizerany/assert;name=assert;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/bmizerany/assert"

# 	github.com/btcsuite/btcd v0.21.0-beta
# [1] git ls-remote https://github.com/btcsuite/btcd 56cc42fe07c206e76812fc57a216b59c41189f04 
SRCREV_btcd="56cc42fe07c206e76812fc57a216b59c41189f04"
SRC_URI += "git://github.com/btcsuite/btcd;name=btcd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/btcsuite/btcd"

# 	github.com/cespare/xxhash/v2 v2.1.2
# [1] git ls-remote https://github.com/cespare/xxhash e7a6b52374f7e2abfb8abb27249d53a1997b09a7 
SRCREV_v2="e7a6b52374f7e2abfb8abb27249d53a1997b09a7"
SRC_URI += "git://github.com/cespare/xxhash;name=v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cespare/xxhash/v2"

# 	github.com/cilium/ebpf v0.7.0
# [1] git ls-remote https://github.com/cilium/ebpf 13667bdb8f164c32ae1b85e7130552dd93e86dfd 
SRCREV_ebpf="13667bdb8f164c32ae1b85e7130552dd93e86dfd"
SRC_URI += "git://github.com/cilium/ebpf;name=ebpf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cilium/ebpf"

# 	github.com/container-orchestrated-devices/container-device-interface v0.3.1
# [1] git ls-remote https://github.com/container-orchestrated-devices/container-device-interface 4b00593bd41bf11254faab4e021a00287e2a7b30 
SRCREV_container-device-interface="4b00593bd41bf11254faab4e021a00287e2a7b30"
SRC_URI += "git://github.com/container-orchestrated-devices/container-device-interface;name=container-device-interface;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/container-orchestrated-devices/container-device-interface"

# 	github.com/containerd/fifo v1.0.0
# [1] git ls-remote https://github.com/containerd/fifo 650e8a8a179d040123db61f016cb133143e7a581 
SRCREV_fifo="650e8a8a179d040123db61f016cb133143e7a581"
SRC_URI += "git://github.com/containerd/fifo;name=fifo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/fifo"

# 	github.com/containerd/ttrpc v1.1.1-0.20220420014843-944ef4a40df3
# [1] git ls-remote https://github.com/containerd/ttrpc 944ef4a40df3446714a823207972b7d9858ffac5 
SRCREV_ttrpc="944ef4a40df3446714a823207972b7d9858ffac5"
SRC_URI += "git://github.com/containerd/ttrpc;name=ttrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/ttrpc"

# 	github.com/containers/ocicrypt v1.1.5
# [1] git ls-remote https://github.com/containers/ocicrypt a468e1acd826dc78e457b308471f90c8eea7551f 
SRCREV_ocicrypt="a468e1acd826dc78e457b308471f90c8eea7551f"
SRC_URI += "git://github.com/containers/ocicrypt;name=ocicrypt;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containers/ocicrypt"

# 	github.com/cpuguy83/go-md2man/v2 v2.0.2
# [1] git ls-remote https://github.com/cpuguy83/go-md2man d97078115282836e16d0dca10b4b42ce60fc70e6 
SRCREV_v21="d97078115282836e16d0dca10b4b42ce60fc70e6"
SRC_URI += "git://github.com/cpuguy83/go-md2man;name=v21;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cpuguy83/go-md2man/v2"

# 	github.com/crackcomm/go-gitignore v0.0.0-20170627025303-887ab5e44cc3
# [1] git ls-remote https://github.com/crackcomm/go-gitignore 887ab5e44cc38866fff9bc2f34c3a97e2a827c12 
SRCREV_go-gitignore="887ab5e44cc38866fff9bc2f34c3a97e2a827c12"
SRC_URI += "git://github.com/crackcomm/go-gitignore;name=go-gitignore;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/crackcomm/go-gitignore"

# 	github.com/distribution/distribution/v3 v3.0.0-20220725133111-4bf3547399eb
# [1] git ls-remote https://github.com/distribution/distribution 4bf3547399eb8a27ee2ec463333c8c456d801345 
SRCREV_v312="4bf3547399eb8a27ee2ec463333c8c456d801345"
SRC_URI += "git://github.com/distribution/distribution;name=v312;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/distribution/distribution/v3"

# 	github.com/djherbis/times v1.5.0
# [1] git ls-remote https://github.com/djherbis/times a1edc5dc082a710e4a808e99c78989b8d04e3025 
SRCREV_times="a1edc5dc082a710e4a808e99c78989b8d04e3025"
SRC_URI += "git://github.com/djherbis/times;name=times;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/djherbis/times"

# 	github.com/docker/distribution v2.8.1+incompatible
# [1] git ls-remote https://github.com/docker/distribution b5ca020cfbe998e5af3457fda087444cf5116496 
SRCREV_distribution="b5ca020cfbe998e5af3457fda087444cf5116496"
SRC_URI += "git://github.com/docker/distribution;name=distribution;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/distribution"

# 	github.com/docker/docker-credential-helpers v0.6.4
# [1] git ls-remote https://github.com/docker/docker-credential-helpers fc9290adbcf1594e78910e2f0334090eaee0e1ee 
SRCREV_docker-credential-helpers="fc9290adbcf1594e78910e2f0334090eaee0e1ee"
SRC_URI += "git://github.com/docker/docker-credential-helpers;name=docker-credential-helpers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker-credential-helpers"

# 	github.com/docker/go-events v0.0.0-20190806004212-e31b211e4f1c
# [1] git ls-remote https://github.com/docker/go-events e31b211e4f1cd09aa76fe4ac244571fab96ae47f 
SRCREV_go-events="e31b211e4f1cd09aa76fe4ac244571fab96ae47f"
SRC_URI += "git://github.com/docker/go-events;name=go-events;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-events"

# 	github.com/docker/go-metrics v0.0.1
# [1] git ls-remote https://github.com/docker/go-metrics b619b3592b65de4f087d9f16863a7e6ff905973c 
SRCREV_go-metrics="b619b3592b65de4f087d9f16863a7e6ff905973c"
SRC_URI += "git://github.com/docker/go-metrics;name=go-metrics;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-metrics"

# 	github.com/fluent/fluent-logger-golang v1.9.0
# [1] git ls-remote https://github.com/fluent/fluent-logger-golang 5538e904aeb515c10a624da620581bdf420d4b8a 
SRCREV_fluent-logger-golang="5538e904aeb515c10a624da620581bdf420d4b8a"
SRC_URI += "git://github.com/fluent/fluent-logger-golang;name=fluent-logger-golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fluent/fluent-logger-golang"

# 	github.com/godbus/dbus/v5 v5.0.6
# [1] git ls-remote https://github.com/godbus/dbus daa017464e266380cdeb4e6f9613eba9182b59a3 
SRCREV_v5="daa017464e266380cdeb4e6f9613eba9182b59a3"
SRC_URI += "git://github.com/godbus/dbus;name=v5;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/godbus/dbus/v5"

# 	github.com/gogo/protobuf v1.3.2
# [1] git ls-remote https://github.com/gogo/protobuf b03c65ea87cdc3521ede29f62fe3ce239267c1bc 
SRCREV_protobuf="b03c65ea87cdc3521ede29f62fe3ce239267c1bc"
SRC_URI += "git://github.com/gogo/protobuf;name=protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/protobuf"

# 	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
# [1] git ls-remote https://github.com/golang/groupcache 41bb18bfe9da5321badc438f91158cd790a33aa3 
SRCREV_groupcache="41bb18bfe9da5321badc438f91158cd790a33aa3"
SRC_URI += "git://github.com/golang/groupcache;name=groupcache;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/groupcache"

# 	github.com/golang/protobuf v1.5.2
# [1] git ls-remote https://github.com/golang/protobuf ae97035608a719c7a1c1c41bed0ae0744bdb0c6f 
SRCREV_protobuf1="ae97035608a719c7a1c1c41bed0ae0744bdb0c6f"
SRC_URI += "git://github.com/golang/protobuf;name=protobuf1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/protobuf"

# 	github.com/google/go-cmp v0.5.8
# [1] git ls-remote https://github.com/google/go-cmp f144a35ed4ac538fae93fa3783175108738f71b9 
SRCREV_go-cmp="f144a35ed4ac538fae93fa3783175108738f71b9"
SRC_URI += "git://github.com/google/go-cmp;name=go-cmp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/go-cmp"

# 	github.com/google/uuid v1.3.0
# [1] git ls-remote https://github.com/google/uuid 44b5fee7c49cf3bcdf723f106b36d56ef13ccc88 
SRCREV_uuid="44b5fee7c49cf3bcdf723f106b36d56ef13ccc88"
SRC_URI += "git://github.com/google/uuid;name=uuid;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/uuid"

# 	github.com/gorilla/mux v1.8.0
# [1] git ls-remote https://github.com/gorilla/mux 98cb6bf42e086f6af920b965c38cacc07402d51b 
SRCREV_mux="98cb6bf42e086f6af920b965c38cacc07402d51b"
SRC_URI += "git://github.com/gorilla/mux;name=mux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gorilla/mux"

# 	github.com/hashicorp/errwrap v1.1.0
# [1] git ls-remote https://github.com/hashicorp/errwrap 7b00e5db719c64d14dd0caaacbd13e76254d02c0 
SRCREV_errwrap="7b00e5db719c64d14dd0caaacbd13e76254d02c0"
SRC_URI += "git://github.com/hashicorp/errwrap;name=errwrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/errwrap"

# 	github.com/hashicorp/golang-lru v0.5.4
# [1] git ls-remote https://github.com/hashicorp/golang-lru 14eae340515388ca95aa8e7b86f0de668e981f54 
SRCREV_golang-lru="14eae340515388ca95aa8e7b86f0de668e981f54"
SRC_URI += "git://github.com/hashicorp/golang-lru;name=golang-lru;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/golang-lru"

# 	github.com/imdario/mergo v0.3.13
# [1] git ls-remote https://github.com/imdario/mergo 194978757031c1a5c8ff8e059ae75fc2fc2a04f7 
SRCREV_mergo="194978757031c1a5c8ff8e059ae75fc2fc2a04f7"
SRC_URI += "git://github.com/imdario/mergo;name=mergo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/imdario/mergo"

# 	github.com/inconshreveable/mousetrap v1.0.0
# [1] git ls-remote https://github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75 
SRCREV_mousetrap="76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
SRC_URI += "git://github.com/inconshreveable/mousetrap;name=mousetrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/inconshreveable/mousetrap"

# 	github.com/ipfs/bbloom v0.0.4
# [1] git ls-remote https://github.com/ipfs/bbloom 627bb99eb0f4c49ab3e3276f5574b9b80f8aa3bc 
SRCREV_bbloom="627bb99eb0f4c49ab3e3276f5574b9b80f8aa3bc"
SRC_URI += "git://github.com/ipfs/bbloom;name=bbloom;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/bbloom"

# 	github.com/ipfs/go-block-format v0.0.3
# [1] git ls-remote https://github.com/ipfs/go-block-format b30b45004baf0d2dcd3d1b5b5604fb4c0ccb0825 
SRCREV_go-block-format="b30b45004baf0d2dcd3d1b5b5604fb4c0ccb0825"
SRC_URI += "git://github.com/ipfs/go-block-format;name=go-block-format;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-block-format"

# 	github.com/ipfs/go-blockservice v0.3.0
# [1] git ls-remote https://github.com/ipfs/go-blockservice 888c7cc7c29cf4752865ce2e856237cb1d5c85b2 
SRCREV_go-blockservice="888c7cc7c29cf4752865ce2e856237cb1d5c85b2"
SRC_URI += "git://github.com/ipfs/go-blockservice;name=go-blockservice;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-blockservice"

# 	github.com/ipfs/go-datastore v0.5.0
# [1] git ls-remote https://github.com/ipfs/go-datastore 7548998537794105418980aeb5dac19802712392 
SRCREV_go-datastore="7548998537794105418980aeb5dac19802712392"
SRC_URI += "git://github.com/ipfs/go-datastore;name=go-datastore;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-datastore"

# 	github.com/ipfs/go-ipfs-blockstore v1.2.0
# [1] git ls-remote https://github.com/ipfs/go-ipfs-blockstore ffd43a8d91e6ee80b26d3a6eca5b8c4816c5508b 
SRCREV_go-ipfs-blockstore="ffd43a8d91e6ee80b26d3a6eca5b8c4816c5508b"
SRC_URI += "git://github.com/ipfs/go-ipfs-blockstore;name=go-ipfs-blockstore;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipfs-blockstore"

# 	github.com/ipfs/go-ipfs-cmds v0.7.0
# [1] git ls-remote https://github.com/ipfs/go-ipfs-cmds ccce9bd6b31f21f74cf4cd1aba43ba17413b9b40 
SRCREV_go-ipfs-cmds="ccce9bd6b31f21f74cf4cd1aba43ba17413b9b40"
SRC_URI += "git://github.com/ipfs/go-ipfs-cmds;name=go-ipfs-cmds;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipfs-cmds"

# 	github.com/ipfs/go-ipfs-ds-help v1.1.0
# [1] git ls-remote https://github.com/ipfs/go-ipfs-ds-help 0ce85d6dd676a9c7d3018dd79f43b2b1d7f31082 
SRCREV_go-ipfs-ds-help="0ce85d6dd676a9c7d3018dd79f43b2b1d7f31082"
SRC_URI += "git://github.com/ipfs/go-ipfs-ds-help;name=go-ipfs-ds-help;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipfs-ds-help"

# 	github.com/ipfs/go-ipfs-exchange-interface v0.1.0
# [1] git ls-remote https://github.com/ipfs/go-ipfs-exchange-interface 2e7c882a034eacabca59c5cd2d9ab959c2da78f7 
SRCREV_go-ipfs-exchange-interface="2e7c882a034eacabca59c5cd2d9ab959c2da78f7"
SRC_URI += "git://github.com/ipfs/go-ipfs-exchange-interface;name=go-ipfs-exchange-interface;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipfs-exchange-interface"

# 	github.com/ipfs/go-ipfs-util v0.0.2
# [1] git ls-remote https://github.com/ipfs/go-ipfs-util f4952d1c5a6a9431d6a4d5ea57c4818e6d199464 
SRCREV_go-ipfs-util="f4952d1c5a6a9431d6a4d5ea57c4818e6d199464"
SRC_URI += "git://github.com/ipfs/go-ipfs-util;name=go-ipfs-util;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipfs-util"

# 	github.com/ipfs/go-ipld-cbor v0.0.5
# [1] git ls-remote https://github.com/ipfs/go-ipld-cbor f689d2bb3874cf3fafb71721cafb2c945234e781 
SRCREV_go-ipld-cbor="f689d2bb3874cf3fafb71721cafb2c945234e781"
SRC_URI += "git://github.com/ipfs/go-ipld-cbor;name=go-ipld-cbor;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipld-cbor"

# 	github.com/ipfs/go-ipld-format v0.4.0
# [1] git ls-remote https://github.com/ipfs/go-ipld-format 0f7aff00f72e9dea0d9718bc0972e309ba7c3e8d 
SRCREV_go-ipld-format="0f7aff00f72e9dea0d9718bc0972e309ba7c3e8d"
SRC_URI += "git://github.com/ipfs/go-ipld-format;name=go-ipld-format;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipld-format"

# 	github.com/ipfs/go-ipld-legacy v0.1.0
# [1] git ls-remote https://github.com/ipfs/go-ipld-legacy 5fff53c64ec247be50252c474053d6720ad3e4d9 
SRCREV_go-ipld-legacy="5fff53c64ec247be50252c474053d6720ad3e4d9"
SRC_URI += "git://github.com/ipfs/go-ipld-legacy;name=go-ipld-legacy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-ipld-legacy"

# 	github.com/ipfs/go-log v1.0.5
# [1] git ls-remote https://github.com/ipfs/go-log c39ee80c0915c5cca41dc1311e848c2fd7fa4101 
SRCREV_go-log="c39ee80c0915c5cca41dc1311e848c2fd7fa4101"
SRC_URI += "git://github.com/ipfs/go-log;name=go-log;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-log"

# 	github.com/ipfs/go-log/v2 v2.3.0
# [1] git ls-remote https://github.com/ipfs/go-log 2c2975b5095a771b0d8066a458b944ac71591bc7 
SRCREV_v212="2c2975b5095a771b0d8066a458b944ac71591bc7"
SRC_URI += "git://github.com/ipfs/go-log;name=v212;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-log/v2"

# 	github.com/ipfs/go-merkledag v0.6.0
# [1] git ls-remote https://github.com/ipfs/go-merkledag c076715ad64cccb1976de3686b0d6304ec3f2839 
SRCREV_go-merkledag="c076715ad64cccb1976de3686b0d6304ec3f2839"
SRC_URI += "git://github.com/ipfs/go-merkledag;name=go-merkledag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-merkledag"

# 	github.com/ipfs/go-metrics-interface v0.0.1
# [1] git ls-remote https://github.com/ipfs/go-metrics-interface 87aa106f53272f064ca7956a6db83f17a553f254 
SRCREV_go-metrics-interface="87aa106f53272f064ca7956a6db83f17a553f254"
SRC_URI += "git://github.com/ipfs/go-metrics-interface;name=go-metrics-interface;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-metrics-interface"

# 	github.com/ipfs/go-path v0.3.0
# [1] git ls-remote https://github.com/ipfs/go-path 91bec98075b9078deeebc1f4f1265b75836a7358 
SRCREV_go-path="91bec98075b9078deeebc1f4f1265b75836a7358"
SRC_URI += "git://github.com/ipfs/go-path;name=go-path;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-path"

# 	github.com/ipfs/go-unixfs v0.3.1
# [1] git ls-remote https://github.com/ipfs/go-unixfs b411ee90ec31ecb290847c37f36fbeb48a9a6a38 
SRCREV_go-unixfs="b411ee90ec31ecb290847c37f36fbeb48a9a6a38"
SRC_URI += "git://github.com/ipfs/go-unixfs;name=go-unixfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-unixfs"

# 	github.com/ipfs/go-verifcid v0.0.1
# [1] git ls-remote https://github.com/ipfs/go-verifcid 34e41ba962e7ce0211a05915f788486c8db755f1 
SRCREV_go-verifcid="34e41ba962e7ce0211a05915f788486c8db755f1"
SRC_URI += "git://github.com/ipfs/go-verifcid;name=go-verifcid;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipfs/go-verifcid"

# 	github.com/ipld/go-codec-dagpb v1.3.2
# [1] git ls-remote https://github.com/ipld/go-codec-dagpb 01c91b765ff1e97d147f2d0e281214a458f59bc0 
SRCREV_go-codec-dagpb="01c91b765ff1e97d147f2d0e281214a458f59bc0"
SRC_URI += "git://github.com/ipld/go-codec-dagpb;name=go-codec-dagpb;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipld/go-codec-dagpb"

# 	github.com/ipld/go-ipld-prime v0.11.0
# [1] git ls-remote https://github.com/ipld/go-ipld-prime d229c642562a92a2d455b20b6f1ef0a11dc96ef2 
SRCREV_go-ipld-prime="d229c642562a92a2d455b20b6f1ef0a11dc96ef2"
SRC_URI += "git://github.com/ipld/go-ipld-prime;name=go-ipld-prime;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ipld/go-ipld-prime"

# 	github.com/jbenet/goprocess v0.1.4
# [1] git ls-remote https://github.com/jbenet/goprocess 23d20c20149e1f362afda26f4500cb9d6393f0ad 
SRCREV_goprocess="23d20c20149e1f362afda26f4500cb9d6393f0ad"
SRC_URI += "git://github.com/jbenet/goprocess;name=goprocess;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/jbenet/goprocess"

# 	github.com/klauspost/compress v1.15.7
# [1] git ls-remote https://github.com/klauspost/compress 07a5f92755d07e86cbdd912c16bd2a528983bd8a 
SRCREV_compress="07a5f92755d07e86cbdd912c16bd2a528983bd8a"
SRC_URI += "git://github.com/klauspost/compress;name=compress;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/klauspost/compress"

# 	github.com/klauspost/cpuid/v2 v2.0.9
# [1] git ls-remote https://github.com/klauspost/cpuid 6903d4066801a7d800d4537ee9eebe81ea97000e 
SRCREV_v2123="6903d4066801a7d800d4537ee9eebe81ea97000e"
SRC_URI += "git://github.com/klauspost/cpuid;name=v2123;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/klauspost/cpuid/v2"

# 	github.com/libp2p/go-buffer-pool v0.0.2
# [1] git ls-remote https://github.com/libp2p/go-buffer-pool c4a5988a1e475884367015e1a2d0bd5fa4c491f4 
SRCREV_go-buffer-pool="c4a5988a1e475884367015e1a2d0bd5fa4c491f4"
SRC_URI += "git://github.com/libp2p/go-buffer-pool;name=go-buffer-pool;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/libp2p/go-buffer-pool"

# 	github.com/libp2p/go-libp2p-core v0.8.6
# [1] git ls-remote https://github.com/libp2p/go-libp2p-core ef6e277df7422a37b1bbd92ac97f933d63d4cd97 
SRCREV_go-libp2p-core="ef6e277df7422a37b1bbd92ac97f933d63d4cd97"
SRC_URI += "git://github.com/libp2p/go-libp2p-core;name=go-libp2p-core;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/libp2p/go-libp2p-core"

# 	github.com/libp2p/go-openssl v0.0.7
# [1] git ls-remote https://github.com/libp2p/go-openssl d9b640282843752442a8f28637156e13b1abd3f4 
SRCREV_go-openssl="d9b640282843752442a8f28637156e13b1abd3f4"
SRC_URI += "git://github.com/libp2p/go-openssl;name=go-openssl;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/libp2p/go-openssl"

# 	github.com/mattn/go-colorable v0.1.12
# [1] git ls-remote https://github.com/mattn/go-colorable e1bb79c8d53c38a60962ad4b8f658226cc983710 
SRCREV_go-colorable="e1bb79c8d53c38a60962ad4b8f658226cc983710"
SRC_URI += "git://github.com/mattn/go-colorable;name=go-colorable;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-colorable"

# 	github.com/mattn/go-shellwords v1.0.12
# [1] git ls-remote https://github.com/mattn/go-shellwords 973b9d5391598d4ee601db46fa32f6e186a356ac 
SRCREV_go-shellwords="973b9d5391598d4ee601db46fa32f6e186a356ac"
SRC_URI += "git://github.com/mattn/go-shellwords;name=go-shellwords;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-shellwords"

# 	github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
# [1] git ls-remote https://github.com/matttproud/golang_protobuf_extensions c182affec369e30f25d3eb8cd8a478dee585ae7d 
SRCREV_golang_protobuf_extensions="c182affec369e30f25d3eb8cd8a478dee585ae7d"
SRC_URI += "git://github.com/matttproud/golang_protobuf_extensions;name=golang_protobuf_extensions;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/matttproud/golang_protobuf_extensions"

# 	github.com/miekg/pkcs11 v1.1.1
# [1] git ls-remote https://github.com/miekg/pkcs11 f3481918a208bd212aa995a41f92d786eb418a7d 
SRCREV_pkcs11="f3481918a208bd212aa995a41f92d786eb418a7d"
SRC_URI += "git://github.com/miekg/pkcs11;name=pkcs11;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/miekg/pkcs11"

# 	github.com/minio/blake2b-simd v0.0.0-20160723061019-3f5f724cb5b1
# [1] git ls-remote https://github.com/minio/blake2b-simd 3f5f724cb5b182a5c278d6d3d55b40e7f8c2efb4 
SRCREV_blake2b-simd="3f5f724cb5b182a5c278d6d3d55b40e7f8c2efb4"
SRC_URI += "git://github.com/minio/blake2b-simd;name=blake2b-simd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/minio/blake2b-simd"

# 	github.com/minio/sha256-simd v1.0.0
# [1] git ls-remote https://github.com/minio/sha256-simd 6a57409d8e0fa3ae883aee331b71aaa40d5a7dd9 
SRCREV_sha256-simd="6a57409d8e0fa3ae883aee331b71aaa40d5a7dd9"
SRC_URI += "git://github.com/minio/sha256-simd;name=sha256-simd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/minio/sha256-simd"

# 	github.com/mitchellh/go-homedir v1.1.0
# [1] git ls-remote https://github.com/mitchellh/go-homedir af06845cf3004701891bf4fdb884bfe4920b3727 
SRCREV_go-homedir="af06845cf3004701891bf4fdb884bfe4920b3727"
SRC_URI += "git://github.com/mitchellh/go-homedir;name=go-homedir;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/go-homedir"

# 	github.com/mitchellh/mapstructure v1.5.0
# [1] git ls-remote https://github.com/mitchellh/mapstructure ab69d8d93410fce4361f4912bb1ff88110a81311 
SRCREV_mapstructure="ab69d8d93410fce4361f4912bb1ff88110a81311"
SRC_URI += "git://github.com/mitchellh/mapstructure;name=mapstructure;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/mapstructure"

# 	github.com/moby/locker v1.0.1
# [1] git ls-remote https://github.com/moby/locker 281af2d563954745bea9d1487c965f24d30742fe 
SRCREV_locker="281af2d563954745bea9d1487c965f24d30742fe"
SRC_URI += "git://github.com/moby/locker;name=locker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/locker"

# 	github.com/moby/sys/mountinfo v0.6.2
# [1] git ls-remote https://github.com/moby/sys 1bf36f7188c31f2797c556c4c4d7d9af7a6a965b 
SRCREV_mountinfo="1bf36f7188c31f2797c556c4c4d7d9af7a6a965b"
SRC_URI += "git://github.com/moby/sys;name=mountinfo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/mountinfo"

# 	github.com/moby/sys/signal v0.7.0
# [1] git ls-remote https://github.com/moby/sys b8d8fabf1fa5cf0de7c1a1729145eee854ea31f5 
SRCREV_signal="b8d8fabf1fa5cf0de7c1a1729145eee854ea31f5"
SRC_URI += "git://github.com/moby/sys;name=signal;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/signal"

# 	github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6
# [1] git ls-remote https://github.com/moby/term 3f7ff695adc6a35abc925370dd0a4dafb48ec64d 
SRCREV_term1="3f7ff695adc6a35abc925370dd0a4dafb48ec64d"
SRC_URI += "git://github.com/moby/term;name=term1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/term"

# 	github.com/morikuni/aec v1.0.0
# [1] git ls-remote https://github.com/morikuni/aec 39771216ff4c63d11f5e604076f9c45e8be1067b 
SRCREV_aec="39771216ff4c63d11f5e604076f9c45e8be1067b"
SRC_URI += "git://github.com/morikuni/aec;name=aec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/morikuni/aec"

# 	github.com/mr-tron/base58 v1.2.0
# [1] git ls-remote https://github.com/mr-tron/base58 cd0e5141f51dfcadb8311fd8e495eb11126a8010 
SRCREV_base58="cd0e5141f51dfcadb8311fd8e495eb11126a8010"
SRC_URI += "git://github.com/mr-tron/base58;name=base58;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mr-tron/base58"

# 	github.com/multiformats/go-base32 v0.0.3
# [1] git ls-remote https://github.com/multiformats/go-base32 a9c2755c3d1672dbe6a7e4a5d182169fa30b6a8e 
SRCREV_go-base32="a9c2755c3d1672dbe6a7e4a5d182169fa30b6a8e"
SRC_URI += "git://github.com/multiformats/go-base32;name=go-base32;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/multiformats/go-base32"

# 	github.com/multiformats/go-base36 v0.1.0
# [1] git ls-remote https://github.com/multiformats/go-base36 dc4afa6ad3b0720f4a1b282776db2a59ca9c8be7 
SRCREV_go-base36="dc4afa6ad3b0720f4a1b282776db2a59ca9c8be7"
SRC_URI += "git://github.com/multiformats/go-base36;name=go-base36;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/multiformats/go-base36"

# 	github.com/multiformats/go-multibase v0.0.3
# [1] git ls-remote https://github.com/multiformats/go-multibase e2260b5ff35e4a37375ca184662ae0b9b0a661be 
SRCREV_go-multibase="e2260b5ff35e4a37375ca184662ae0b9b0a661be"
SRC_URI += "git://github.com/multiformats/go-multibase;name=go-multibase;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/multiformats/go-multibase"

# 	github.com/multiformats/go-multicodec v0.4.1
# [1] git ls-remote https://github.com/multiformats/go-multicodec 9a49a9b749f87f772b72c9482f704df54ccd88ea 
SRCREV_go-multicodec="9a49a9b749f87f772b72c9482f704df54ccd88ea"
SRC_URI += "git://github.com/multiformats/go-multicodec;name=go-multicodec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/multiformats/go-multicodec"

# 	github.com/multiformats/go-multihash v0.1.0
# [1] git ls-remote https://github.com/multiformats/go-multihash 679c1b0a0a184d364ebb4768566143d21be4a5fb 
SRCREV_go-multihash="679c1b0a0a184d364ebb4768566143d21be4a5fb"
SRC_URI += "git://github.com/multiformats/go-multihash;name=go-multihash;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/multiformats/go-multihash"

# 	github.com/multiformats/go-varint v0.0.6
# [1] git ls-remote https://github.com/multiformats/go-varint a3ded45ab16ca9f2f2a516e68053ffa7ebd9bb0e 
SRCREV_go-varint="a3ded45ab16ca9f2f2a516e68053ffa7ebd9bb0e"
SRC_URI += "git://github.com/multiformats/go-varint;name=go-varint;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/multiformats/go-varint"

# 	github.com/opencontainers/runc v1.1.2
# [1] git ls-remote https://github.com/opencontainers/runc a916309fff0f838eb94e928713dbc3c0d0ac7aa4 
SRCREV_runc="a916309fff0f838eb94e928713dbc3c0d0ac7aa4"
SRC_URI += "git://github.com/opencontainers/runc;name=runc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/runc"

# 	github.com/opencontainers/runtime-tools v0.0.0-20190417131837-cd1349b7c47e
# [1] git ls-remote https://github.com/opencontainers/runtime-tools cd1349b7c47e9def74bee83f6cec88c5c3413e65 
SRCREV_runtime-tools="cd1349b7c47e9def74bee83f6cec88c5c3413e65"
SRC_URI += "git://github.com/opencontainers/runtime-tools;name=runtime-tools;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/runtime-tools"

# 	github.com/opencontainers/selinux v1.10.1
# [1] git ls-remote https://github.com/opencontainers/selinux 84e248a28e776216cd33a51fdea90a20fe308136 
SRCREV_selinux="84e248a28e776216cd33a51fdea90a20fe308136"
SRC_URI += "git://github.com/opencontainers/selinux;name=selinux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/selinux"

# 	github.com/opentracing/opentracing-go v1.2.0
# [1] git ls-remote https://github.com/opentracing/opentracing-go d34af3eaa63c4d08ab54863a4bdd0daa45212e12 
SRCREV_opentracing-go="d34af3eaa63c4d08ab54863a4bdd0daa45212e12"
SRC_URI += "git://github.com/opentracing/opentracing-go;name=opentracing-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opentracing/opentracing-go"

# 	github.com/philhofer/fwd v1.1.1
# [1] git ls-remote https://github.com/philhofer/fwd 9bcb9cab1b0394d8516a132ec243ba944efdb644 
SRCREV_fwd="9bcb9cab1b0394d8516a132ec243ba944efdb644"
SRC_URI += "git://github.com/philhofer/fwd;name=fwd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/philhofer/fwd"

# 	github.com/pkg/errors v0.9.1
# [1] git ls-remote https://github.com/pkg/errors 614d223910a179a466c1767a985424175c39b465 
SRCREV_errors="614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors;name=errors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pkg/errors"

# 	github.com/polydawn/refmt v0.0.0-20201211092308-30ac6d18308e
# [1] git ls-remote https://github.com/polydawn/refmt 30ac6d18308e584ca6a2e74ba81475559db94c5f 
SRCREV_refmt="30ac6d18308e584ca6a2e74ba81475559db94c5f"
SRC_URI += "git://github.com/polydawn/refmt;name=refmt;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/polydawn/refmt"

# 	github.com/prometheus/client_golang v1.12.2
# [1] git ls-remote https://github.com/prometheus/client_golang e203144f43306c1f344fbc548fd02c4b79962e30 
SRCREV_client_golang="e203144f43306c1f344fbc548fd02c4b79962e30"
SRC_URI += "git://github.com/prometheus/client_golang;name=client_golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_golang"

# 	github.com/prometheus/client_model v0.2.0
# [1] git ls-remote https://github.com/prometheus/client_model 7bc5445566f0fe75b15de23e6b93886e982d7bf9 
SRCREV_client_model="7bc5445566f0fe75b15de23e6b93886e982d7bf9"
SRC_URI += "git://github.com/prometheus/client_model;name=client_model;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_model"

# 	github.com/prometheus/common v0.32.1
# [1] git ls-remote https://github.com/prometheus/common 2af6d036253eee1a9a08c6ddf6be6d67537bcdff 
SRCREV_common="2af6d036253eee1a9a08c6ddf6be6d67537bcdff"
SRC_URI += "git://github.com/prometheus/common;name=common;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/common"

# 	github.com/prometheus/procfs v0.7.3
# [1] git ls-remote https://github.com/prometheus/procfs f436cbb89ece38bf080d446b3ca27053b305eaac 
SRCREV_procfs="f436cbb89ece38bf080d446b3ca27053b305eaac"
SRC_URI += "git://github.com/prometheus/procfs;name=procfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/procfs"

# 	github.com/rs/cors v1.7.0
# [1] git ls-remote https://github.com/rs/cors db0fe48135e83b5812a5a31be0eea66984b1b521 
SRCREV_cors="db0fe48135e83b5812a5a31be0eea66984b1b521"
SRC_URI += "git://github.com/rs/cors;name=cors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/rs/cors"

# 	github.com/russross/blackfriday/v2 v2.1.0
# [1] git ls-remote https://github.com/russross/blackfriday 4c9bf9512682b995722660a4196c0013228e2049 
SRCREV_v21234="4c9bf9512682b995722660a4196c0013228e2049"
SRC_URI += "git://github.com/russross/blackfriday;name=v21234;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/russross/blackfriday/v2"

# 	github.com/spacemonkeygo/spacelog v0.0.0-20180420211403-2296661a0572
# [1] git ls-remote https://github.com/spacemonkeygo/spacelog 2296661a0572a51438413369004fa931c2641923 
SRCREV_spacelog="2296661a0572a51438413369004fa931c2641923"
SRC_URI += "git://github.com/spacemonkeygo/spacelog;name=spacelog;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spacemonkeygo/spacelog"

# 	github.com/spaolacci/murmur3 v1.1.0
# [1] git ls-remote https://github.com/spaolacci/murmur3 f09979ecbc725b9e6d41a297405f65e7e8804acc 
SRCREV_murmur3="f09979ecbc725b9e6d41a297405f65e7e8804acc"
SRC_URI += "git://github.com/spaolacci/murmur3;name=murmur3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spaolacci/murmur3"

# 	github.com/stefanberger/go-pkcs11uri v0.0.0-20201008174630-78d3cae3a980
# [1] git ls-remote https://github.com/stefanberger/go-pkcs11uri 78d3cae3a9805d89aa4fa80a362ca944c89a1b99 
SRCREV_go-pkcs11uri="78d3cae3a9805d89aa4fa80a362ca944c89a1b99"
SRC_URI += "git://github.com/stefanberger/go-pkcs11uri;name=go-pkcs11uri;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stefanberger/go-pkcs11uri"

# 	github.com/syndtr/gocapability v0.0.0-20200815063812-42c35b437635
# [1] git ls-remote https://github.com/syndtr/gocapability 42c35b4376354fd554efc7ad35e0b7f94e3a0ffb 
SRCREV_gocapability="42c35b4376354fd554efc7ad35e0b7f94e3a0ffb"
SRC_URI += "git://github.com/syndtr/gocapability;name=gocapability;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/syndtr/gocapability"

# 	github.com/tidwall/match v1.1.1
# [1] git ls-remote https://github.com/tidwall/match 4c9fc61b493b7aa0a3d347e9190aa78c5bec09cf 
SRCREV_match="4c9fc61b493b7aa0a3d347e9190aa78c5bec09cf"
SRC_URI += "git://github.com/tidwall/match;name=match;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tidwall/match"

# 	github.com/tidwall/pretty v1.2.0
# [1] git ls-remote https://github.com/tidwall/pretty aaa765e7476acb0028a854b85675801362cbdaa2 
SRCREV_pretty="aaa765e7476acb0028a854b85675801362cbdaa2"
SRC_URI += "git://github.com/tidwall/pretty;name=pretty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tidwall/pretty"

# 	github.com/tinylib/msgp v1.1.6
# [1] git ls-remote https://github.com/tinylib/msgp 205265da651409c54677b486e350b4d105da6d8b 
SRCREV_msgp="205265da651409c54677b486e350b4d105da6d8b"
SRC_URI += "git://github.com/tinylib/msgp;name=msgp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tinylib/msgp"

# 	github.com/urfave/cli v1.22.9
# [1] git ls-remote https://github.com/urfave/cli 575b8b484800dff928fe8755d61fea64571bc191 
SRCREV_cli1="575b8b484800dff928fe8755d61fea64571bc191"
SRC_URI += "git://github.com/urfave/cli;name=cli1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/urfave/cli"

# 	github.com/vbatts/tar-split v0.11.2
# [1] git ls-remote https://github.com/vbatts/tar-split 80a436fd6164c557b131f7c59ed69bd81af69761 
SRCREV_tar-split="80a436fd6164c557b131f7c59ed69bd81af69761"
SRC_URI += "git://github.com/vbatts/tar-split;name=tar-split;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/vbatts/tar-split"

# 	github.com/whyrusleeping/cbor-gen v0.0.0-20200123233031-1cdf64d27158
# [1] git ls-remote https://github.com/whyrusleeping/cbor-gen 1cdf64d27158b5db2dd11d30591f4a9be0cd55ab 
SRCREV_cbor-gen="1cdf64d27158b5db2dd11d30591f4a9be0cd55ab"
SRC_URI += "git://github.com/whyrusleeping/cbor-gen;name=cbor-gen;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/whyrusleeping/cbor-gen"

# 	github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
# [1] git ls-remote https://github.com/xeipuuv/gojsonpointer 4e3ac2762d5f479393488629ee9370b50873b3a6 
SRCREV_gojsonpointer="4e3ac2762d5f479393488629ee9370b50873b3a6"
SRC_URI += "git://github.com/xeipuuv/gojsonpointer;name=gojsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonpointer"

# 	github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
# [1] git ls-remote https://github.com/xeipuuv/gojsonreference bd5ef7bd5415a7ac448318e64f11a24cd21e594b 
SRCREV_gojsonreference="bd5ef7bd5415a7ac448318e64f11a24cd21e594b"
SRC_URI += "git://github.com/xeipuuv/gojsonreference;name=gojsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonreference"

# 	github.com/xeipuuv/gojsonschema v1.2.0
# [1] git ls-remote https://github.com/xeipuuv/gojsonschema 82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927 
SRCREV_gojsonschema="82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927"
SRC_URI += "git://github.com/xeipuuv/gojsonschema;name=gojsonschema;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonschema"

# 	go.mozilla.org/pkcs7 v0.0.0-20200128120323-432b2356ecb1
# [1] git ls-remote https://github.com/mozilla-services/pkcs7 432b2356ecb18209c1cec25680b8a23632794f21 
SRCREV_pkcs7="432b2356ecb18209c1cec25680b8a23632794f21"
SRC_URI += "git://github.com/mozilla-services/pkcs7;name=pkcs7;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.mozilla.org/pkcs7"

# 	go.opencensus.io v0.23.0
# [1] git ls-remote https://github.com/census-instrumentation/opencensus-go 49838f207d61097fc0ebb8aeef306913388376ca 
SRCREV_go.opencensus.io="49838f207d61097fc0ebb8aeef306913388376ca"
SRC_URI += "git://github.com/census-instrumentation/opencensus-go;name=go.opencensus.io;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opencensus.io"

# 	go.uber.org/atomic v1.7.0
# [1] git ls-remote https://github.com/uber-go/atomic 12f27ba2637fa0e13772a4f05fa46a5d18d53182 
SRCREV_atomic="12f27ba2637fa0e13772a4f05fa46a5d18d53182"
SRC_URI += "git://github.com/uber-go/atomic;name=atomic;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/atomic"

# 	go.uber.org/multierr v1.7.0
# [1] git ls-remote https://github.com/uber-go/multierr a5cd5509686189240486545be669e1dff9b98dcf 
SRCREV_multierr="a5cd5509686189240486545be669e1dff9b98dcf"
SRC_URI += "git://github.com/uber-go/multierr;name=multierr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/multierr"

# 	go.uber.org/zap v1.19.0
# [1] git ls-remote https://github.com/uber-go/zap c8e813efff7b3d6f791ee71b3f76b9a175d2a9d8 
SRCREV_zap="c8e813efff7b3d6f791ee71b3f76b9a175d2a9d8"
SRC_URI += "git://github.com/uber-go/zap;name=zap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/zap"

# 	golang.org/x/text v0.3.7
# [1] git ls-remote https://github.com/golang/text 383b2e75a7a4198c42f8f87833eefb772868a56f 
SRCREV_text="383b2e75a7a4198c42f8f87833eefb772868a56f"
SRC_URI += "git://github.com/golang/text;name=text;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/text"

# 	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
# [1] git ls-remote https://github.com/golang/xerrors 5ec99f83aff198f5fbd629d6c8d8eb38a04218ca 
SRCREV_xerrors="5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
SRC_URI += "git://github.com/golang/xerrors;name=xerrors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/xerrors"

# 	google.golang.org/genproto v0.0.0-20220426171045-31bebdecfb46
# [1] git ls-remote https://github.com/googleapis/go-genproto 31bebdecfb464d262a96789910f0734fa1ce04f6 
SRCREV_genproto="31bebdecfb464d262a96789910f0734fa1ce04f6"
SRC_URI += "git://github.com/googleapis/go-genproto;name=genproto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/go-genproto"

# 	google.golang.org/grpc v1.47.0
# [1] git ls-remote https://github.com/grpc/grpc-go 5b509df1e30a25b14dba119c09295924c9e17abe 
SRCREV_grpc="5b509df1e30a25b14dba119c09295924c9e17abe"
SRC_URI += "git://github.com/grpc/grpc-go;name=grpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc/grpc-go"

# 	google.golang.org/protobuf v1.28.0
# [1] git ls-remote https://github.com/protocolbuffers/protobuf-go 32051b4f86e54c2142c7c05362c6e96ae3454a1c 
SRCREV_protobuf12="32051b4f86e54c2142c7c05362c6e96ae3454a1c"
SRC_URI += "git://github.com/protocolbuffers/protobuf-go;name=protobuf12;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/protocolbuffers/protobuf-go"

# 	gopkg.in/square/go-jose.v2 v2.5.1
# [1] git ls-remote https://gopkg.in/square/go-jose.v2 3a5ee095dcb5030a9de84fb92c222ac652fff176 
SRCREV_go-jose.v2="3a5ee095dcb5030a9de84fb92c222ac652fff176"
SRC_URI += "git://gopkg.in/square/go-jose.v2;name=go-jose.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/square/go-jose.v2"

# 	gopkg.in/yaml.v2 v2.4.0
# [1] git ls-remote https://gopkg.in/yaml.v2 7649d4548cb53a614db133b2a8ac1f31859dda8c 
SRCREV_yaml.v2="7649d4548cb53a614db133b2a8ac1f31859dda8c"
SRC_URI += "git://gopkg.in/yaml.v2;name=yaml.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v2"

# 	lukechampine.com/blake3 v1.1.6
# [1] git ls-remote https://github.com/lukechampine/blake3 09d3897aaa0fdbc603afcf54cfe25bf5d677a6b4 
SRCREV_blake3="09d3897aaa0fdbc603afcf54cfe25bf5d677a6b4"
SRC_URI += "git://github.com/lukechampine/blake3;name=blake3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/lukechampine.com/blake3"

# 	sigs.k8s.io/yaml v1.3.0
# [1] git ls-remote https://github.com/kubernetes-sigs/yaml 9535b3b1e2893fe44efb37c5c9f5665e245d786a 
SRCREV_yaml="9535b3b1e2893fe44efb37c5c9f5665e245d786a"
SRC_URI += "git://github.com/kubernetes-sigs/yaml;name=yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/yaml"

# github.com/containerd/containerd v1.6.1-0.20220621192144-0fac756b6452
# [1] git ls-remote https://github.com/containerd/containerd 0fac756b645275aa855f3d5ab7d1dfd74fadc1ed 
SRCREV_containerd="0fac756b645275aa855f3d5ab7d1dfd74fadc1ed"
SRC_URI += "git://github.com/containerd/containerd;name=containerd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/containerd"

# github.com/ktock/golang-lru v0.5.5-0.20211029085301-ec551be6f75c
# [1] git ls-remote https://github.com/ktock/golang-lru ec551be6f75c10a4f18e3c70a823d03420ee3d4f 
SRCREV_golang-lru1="ec551be6f75c10a4f18e3c70a823d03420ee3d4f"
SRC_URI += "git://github.com/ktock/golang-lru;name=golang-lru1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/golang-lru"

