#!/bin/sh -e

# Use stderr for logging err output in libaktualizr
export LOG_STDERR=1

LOGLEVEL="${CREDS_LOGLEVEL-4}"

if [ "$1" = "get" ] ; then
	exec /usr/bin/aktualizr-get --loglevel $LOGLEVEL -u https://ota-lite.foundries.io:8443/hub-creds/
fi
