name: Backport labeled merged pull requests
on:
  pull_request_target:
    types: [closed]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Create backport PRs
    runs-on: ubuntu-latest
    # Only run when pull request is merged
    # or when a comment containing `/backport` is created
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v4
      - name: Create backport PRs
        uses: korthout/backport-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
